disabled_rules:
  - force_cast
  - force_try
  - function_body_length
  - todo
  - identifier_name
  - type_body_length
  - line_length
  - comma
  - multiple_closures_with_trailing_closure
  - nesting
  - fallthrough
  - let_var_whitespace
  - switch_case_alignment

opt_in_rules: # some rules are only opt-in
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - deployment_target
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_objc_attribute
  - redundant_type_annotation
  - redundant_nil_coalescing
  - shorthand_operator
  - sorted_imports
  - switch_case_on_newline
  - unused_import
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

  # Find all the available rules by running:
# swiftlint rules
force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

excluded:
  - Pods
file_length:
  warning: 500
  error: 1500

cyclomatic_complexity:
  warning: 20
  error: 50

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50

line_length: 140

type_body_length:
  warning: 200
  error: 400

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50

implicitly_unwrapped_optional:
  severity: error

reporter: 'xcode'
