language: swift
osx_image: xcode11.3
xcode_workspace: IFF.xcworkspace

env:
  global:
    - PROJECT="IFF.xcworkspace"
    - SCHEME="Italian Food Forever"
    - IOS_SDK="iphonesimulator"
  matrix:
    - SDK="$IOS_SDK" DESTINATION="platform=iOS Simulator,OS=13.3,name=iPhone 11"

before_install:
  - brew install cocoapods
  - pod install

install:
  - swift --version

before_script:
  - set -o pipefail

script:
  - xcodebuild clean build
    -workspace "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION" | xcpretty -c
