
# A list of devices you want to take the screenshots from
devices([
    "iPhone 8 Plus",
    "iPhone 11 Pro"
])

# The name of the scheme which contains the UI Tests
scheme("Italian Food ForeverUITests")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

